### ISSUE TITLE
A few syntax errors  (I think..)

### ISSUE THREAD

**Issue by davidfof13** [HPCE/hpce_2014_cw3#10]
In ex4, when you ask us to create the class for src/your_login/direct_fourier_transform_chunked.cpp,  I belive there's a typo  when you asks us to create the  name hpce.your_login.direct_fourier_transform_parfor_chunked ?

Also in ex4, in the environment variables section, isn't getopt supposed to be getenv?

**Comment by m8pple** [comment]
Yes, thanks for that.
