### ISSUE TITLE
Task group & or = for closures 

### ISSUE THREAD

**Issue by kronocharia** [HPCE/hpce_2014_cw3#11]
For the second part, it seems to work with both but I remeber you saying always try and use = where possible, does that still hold here?

**Comment by m8pple** [comment]
Yes, generally it is better to capture using [=], as it minimises the change of accidentally
capturing a mutable reference to shared state.

So if I do:

```
uint32_t x;

parallel_invoke(
    [=](){ x++; },
    [=](){ x=3; }
);
```

each task would get it's own copy of x, and I would notice there was a problem
as the external value of x didn't change.

If I did:

```
uint32_t x;

parallel_invoke(
    [&](){ x++; },
    [&](){ x=3; }
);
```

then x would end up with a different value, but I might not notice the error (it might be
correct by chance).

It is not perfect though, as [=] only says that variables should be captured by value, so
it doesn't help as much with pointers.
