### ISSUE TITLE
Syntax error Section 4

### ISSUE THREAD

**Issue by bwh10** [HPCE/hpce_2014_cw3#3]
In the section Partitioners and grain size, the following syntax is given:

tbb::parallel_for(range, f, tbb::simple_partitioner);

However, the above cannot be compiled when I use VS2012. From https://www.threadingbuildingblocks.org/docs/help/tbb_userguide/Controlling_Chunking.htm, the correct syntax should be the following:

tbb::parallel_for(range, f, tbb::simple_partitioner());

Using the above syntax allows me to compile the above code fine.

**Comment by m8pple** [comment]
Thanks for all of those, it's greatly appreciated, especially with the fixes. You managed
to quite effectively identify the parts that I've changed since last year (I'm trying to
get people to think more about agglomeration and chunking), which doesn't speak
well to my testing.
