### ISSUE TITLE
Why the US Servers  for AWS and not ones in EU?

### ISSUE THREAD

**Issue by kronocharia** [HPCE/hpce_2014_cw3#8]
would I get less of a lag in the prompt if I used a microinstance in say ireland instead?

**Comment by m8pple** [comment]
Sorry for the delayed response.
There should be essentially no difference between US and EU servers except for:
- Price: some zones are more expensive; from memory the Tokyo ones are more expensive
- :Latency: as you note, the EU ones probably have better latency.
- Regulatory area: the NSA/FBI can probably more easily read you code in virginia, GCHQ can more easily read it in the EU. But they can read you stuff either way, so it only matters for compliance really.

So go for EU servers if you prefer.
