### ISSUE TITLE
CMake file

### ISSUE THREAD

**Issue by kronocharia** [HPCE/hpce_2014_cw3#9]
Any chance I could get a CMake file with the basics stuff like you have for nmake and make?

**Comment by m8pple** [comment]
I'm afraid I don't remember CMakeLists.txt syntax well enough to write one without some
reading and time. There appear to be some converters available:
http://www.cmake.org/Wiki/CMake#Converters_from_other_buildsystems_to_CMake
but I don't know how well they work.

If you create one, I'd happily integrate it into the distribution though.
